import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const sopsDir = join(import.meta.dirname, 'sops');
const outFile = join(import.meta.dirname, 'sops-bundle.ts');

const files = readdirSync(sopsDir).filter(f => f.endsWith('.md'));

const entries = files.map(file => {
  const content = readFileSync(join(sopsDir, file), 'utf-8');
  const key = basename(file, '.md').replace(/[^a-zA-Z0-9]/g, '_');
  return { key, file, content };
});

const lines = [
  '// Auto-generated by bundle-sops.ts — do not edit manually',
  '',
  ...entries.map(e =>
    `export const ${e.key} = ${JSON.stringify(e.content)};`
  ),
  '',
  'export const allSops: Record<string, string> = {',
  ...entries.map(e => `  '${e.file}': ${e.key},`),
  '};',
  '',
];

writeFileSync(outFile, lines.join('\n'));
console.log(`Bundled ${entries.length} SOP(s) into sops-bundle.ts`);
